Updated-01-13-2016-17:53

diff --git a/bash_func b/bash_func
--- a/bash_func
+++ b/bash_func
@@ -67,9 +67,10 @@ function copy_file()
 function clean_file()
 {
 	#echo "Clean file $1 ..."
+	temp=$EXITONERROR
 	EXITONERROR="no"
 	run_cmd rm -rf $1
-	EXITONERROR="yes"
+	EXITONERROR=$temp
 }
 
 # get_file <file name> <file url> <back up file>
@@ -82,16 +83,21 @@ function get_file()
         if [ -f $1 ]; then
                 run_cmd rm -f $1
         fi
+	temp=$EXITONERROR
         EXITONERROR="no"
         run_cmd wget $2 -O $1
+        EXITONERROR=$temp
         if [ "$ret" -ne "0" ]; then
                 echo "Error on retriving $1 ..."
                 if [ -f $3 ]; then
                         echo "Using $3 files ..."
                         copy_file $3 $1
+			return 0
+		else
+			echo "No backup file ..."
+			return 1
                 fi
         fi
-        EXITONERROR="yes"
 }
 
 function get_version()
@@ -305,6 +311,75 @@ function link_draft()
 	fi 
 }
 
+function jenkins_get_cli()
+{
+	if [ "$is_java" -eq 0 ] 
+	then
+		echo "Java not found ..."
+		echo "jenkins-cli need java ..."
+	else
+    		if [ -f ft_bin/jenkins-cli.jar ]
+		then
+			echo "jenkins-cli found ..."
+			is_jenkins_cli=1
+		else
+                        echo "jenkins-cli not found ..."
+			is_jenkins_cli=0
+			get_file ft_bin/jenkins-cli.jar $JENKINS_URL/jnlpJars/jenkins-cli.jar
+		fi
+	fi
+}
+
+function jenkins_cli_run()
+{
+	if [ "$is_java" -eq 1 ] && [ "$is_jenkins_cli" -eq 1 ]
+	then
+		run_cmd java -jar ft_bin/jenkins-cli.jar -s $JENKINS_URL/ $@
+    	fi
+}
+
+function jenkins_check_auth()
+{	
+	temp=$run_cmd_debug
+	run_cmd_debug=1
+	is_auth=$(jenkins_cli_run who-am-i | grep "authenticated" | wc -l)
+	run_cmd_debug=$temp
+	if [ "$is_auth" -eq 1 ]
+	then
+		echo "The jenkins is authanticated ..."
+	else
+		echo "The jenkins is not authaticated ($is_auth) ..."
+		is_auth=0
+	fi
+}
+
+function jenkins_get_all_jobs()
+{
+        if [ "$is_auth" -eq 1 ] 
+        then
+		for temp_jobs in $(echo $JENKINS_JOBS | sed "s/,/ /g")
+		do
+			echo "Getting XML configuration for $temp_jobs ..."
+			if [ -d $temp_jobs ]; then
+				mkdir $temp_jobs
+			fi
+    			jenkins_cli_run get-job $temp_jobs > $temp_jobs/job.xml
+		done
+	else
+		exit 1
+	fi
+}
+
+function jenkins_get_plugins()
+{
+        if [ "$is_auth" -eq 1 ]
+        then
+		echo "Getting list of plugins ..."
+                jenkins_cli_run list-plugins >  list-plugins.txt
+        else
+                exit 1
+        fi
+}
+
 set_default
 trap $EXITFUN 1 2 3 6 15
-
